export const city = {
	port:[
		{
			idx:0,cityName:'Ganghwa',mapIdx:0,position:[10,20],price:1,
			toolShop:{accessory:[],upgrade:[{idx:0},{idx:1},{idx:2},{idx:6},{idx:7},{idx:8}],etc:[{idx:3},{idx:4},{idx:5},{idx:6},{idx:7},{idx:8},{idx:9},{idx:10},{idx:20},{idx:22}]},
			equipmentShop:{helm:[],armor:[],weapon:[]},
			tradingPost:[],
			shipyard:{
				blueprint:[30],
				wood:[0,3,4,5,7],
				sail:[0,1,2,5],
				figure:[0,5,6,7,20,22,35,40,47],
				anchor:[0,1,2,6],
				cannon:[0,1,2,3,4,5,6]
			}
		}, 
		{idx:1,cityName:'Ulsan',price:1,toolShop:{},equipmentShop:{},tradingPost:[]},
		{idx:2,cityName:'Hanyang',price:1,toolShop:{},equipmentShop:{},tradingPost:[]},
		{idx:3,},
		{idx:4,},
		{idx:5,},
		{idx:6,},
		{idx:7,},
		{idx:8,},
	]
}