// heros country 값으로 국가 판단 country 국가(일본0, 한국1, 몽골2, 중국3, 사우디아라비아4, 이집트5, 그리스6, 이탈리아7, 프랑스8, 스페인9, 포르투칼10, 영국11)
//hole 1방어, 4체력, 7행운, 10공격, 13술법공격, 16술법방어, 19속도, 22행동, 
export const drop = {
  itemNum: {//획득 아이템 갯수
    exploring: 1,
    scenarioRegion: 2,
    regionMove: 2,
  },
  country: [//캐릭터 출신국가
    {// 읿본
      head: [5],
      armor: [8],
      weapon: [1,7],
      ring: [],
      amulet: [],
      hole: [19],
      upgrade: [],
      material: [],
      etc:[31],
      money:0,
    },
    {// 한국
      head: [1],
      armor: [0,9],
      weapon: [3,6],
      ring: [],
      amulet: [],
      hole: [10],
      upgrade: [],
      material: [],
      etc:[32],
      money:0,
    },
    {// 몽골
      head: [1],
      armor: [0,1],
      weapon: [0,6],
      ring: [],
      amulet: [],
      hole: [19],
      upgrade: [],
      material: [],
      etc:[33],
      money:0,
    },
    {// 중국
      head: [2],
      armor: [2],
      weapon: [4,7],
      ring: [],
      amulet: [],
      hole: [4],
      upgrade: [],
      material: [],
      etc:[34],
      money:0,
    },
    {// 사우디
      head: [0],
      armor: [2],
      weapon: [0,5],
      ring: [],
      amulet: [],
      hole: [7],
      upgrade: [],
      material: [],
      etc:[35],
      money:0,
    },
    {// 이집트
      head: [0],
      armor: [3],
      weapon: [0,8],
      ring: [],
      amulet: [],
      hole: [13],
      upgrade: [],
      material: [],
      etc:[36],
      money:0,
    },
    {// 그리스
      head: [3],
      armor: [0,4],
      weapon: [4,5],
      ring: [],
      amulet: [],
      hole: [22],
      upgrade: [],
      material: [],
      etc:[37],
      money:0,
    },
    {// 이탈리아
      head: [4],
      armor: [6],
      weapon: [1,2],
      ring: [],
      amulet: [],
      hole: [16],
      upgrade: [],
      material: [],
      etc:[38],
      money:0,
    },
    {// 프랑스
      head: [4],
      armor: [7],
      weapon: [2,7],
      ring: [],
      amulet: [],
      hole: [13],
      upgrade: [],
      material: [],
      etc:[39],
      money:0,
    },
    {// 스페인
      head: [6],
      armor: [5],
      weapon: [1,3],
      ring: [],
      amulet: [],
      hole: [22],
      upgrade: [],
      material: [],
      etc:[40],
      money:0,
    },
    {// 포루투갈
      head: [6],
      armor: [10],
      weapon: [0,5],
      ring: [],
      amulet: [],
      hole: [10],
      upgrade: [],
      material: [],
      etc:[41],
      money:0,
    },
    {// 영국
      head: [7],
      armor: [11],
      weapon: [2,8],
      ring: [],
      amulet: [],
      hole: [1],
      upgrade: [],
      material: [],
      etc:[42],
      money:0,
    },
  ],
  stay: [//현재 지역
    {// 읿본
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [19],
      upgrade: [],
      material: [0,1,29,40,48,52],
      etc:[],
      money:0,
    },
    {// 한국
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [10],
      upgrade: [],
      material: [0,1,21,37,44],
      etc:[],
      money:0,
    },
    {// 몽골
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [19],
      upgrade: [],
      material: [0,1,41],
      etc:[],
      money:0,
    },
    {// 중국
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [4],
      upgrade: [],
      material: [0,1,3,9,18,22,44],
      money:0,
    },
    {// 사우디
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [7],
      upgrade: [],
      material: [0,1,5,10,54],
      etc:[],
      money:0,
    },
    {// 이집트
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [13],
      upgrade: [],
      material: [0,1,10,53],
      etc:[],
      money:0,
    },
    {// 그리스
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [22],
      upgrade: [],
      material: [0,1,34,35,36,49,51],
      etc:[],
      money:0,
    },
    {// 이탈리아
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [16],
      upgrade: [],
      material: [0,1,7,28,43,45],
      etc:[],
      money:0,
    },
    {// 프랑스
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [13],
      upgrade: [],
      material: [0,1,2,4,11,14,23,26],
      etc:[],
      money:0,
    },
    {// 스페인
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [22],
      upgrade: [],
      material: [0,1,6,8,16,20,25,31,32,46,47],
      etc:[],
      money:0,
    },
    {// 포루투갈
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [10],
      upgrade: [],
      material: [0,1,12,15,17,39],
      etc:[],
      money:0,
    },
    {// 영국
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [1],
      upgrade: [],
      material: [0,1,13,19,24,27,30,33,38,42,50,52,55],
      etc:[],
      money:0,
    },
  ],
  lv: [
    {// 10
      head: [0],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        1,4,7,10,13,16,19,22
      ],
      upgrade: [0,6],
      material: [],
      etc:[],
      money:100,
    },
    {// 20
      head: [0],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        1,4,7,10,13,16,19,22,
        1,4,7,10,13,16,19,22,
        2,5,8,11,14,17,20,23
      ],
      upgrade: [0,1,6,7],
      material: [],
      etc:[],
      money:200,
    },
    {// 30
      head: [0],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        1,4,7,10,13,16,19,22,
        2,5,8,11,14,17,20,23
      ],
      upgrade: [0,1,2,6,7,8],
      material: [],
      etc:[],
      money:300,
    },
    {// 40
      head: [0],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        1,4,7,10,13,16,19,22,
        2,5,8,11,14,17,20,23,
        2,5,8,11,14,17,20,23,
        3,6,9,12,15,18,21,24
      ],
      upgrade: [1,2,3,7,8,9],
      material: [],
      etc:[],
      money:400,
    },
    {// 50
      head: [0],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        2,5,8,11,14,17,20,23,
        2,5,8,11,14,17,20,23,
        3,6,9,12,15,18,21,24
      ],
      upgrade: [2,3,4,8,9,10],
      material: [],
      etc:[],
      money:500,
    },
  ],
  region: [
    {// 태평양(아시아 -> 아메리카)
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        3,15,
        100,101,102,103,104,121,122,123,124,
        100,101,102,103,104,121,122,123,124
      ],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    {// 북극해(아시아 -> 아메리카)
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        6,18,
        100,105,106,107,108,125,126,127,128,
        100,105,106,107,108,125,126,127,128
      ],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    {// 대서양(아메리카 -> 아프리카 & 유럽)
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        9,21,
        100,109,110,111,112,129,130,131,132,
        100,109,110,111,112,129,130,131,132
      ],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    {// 지중해(중동 -> 아프리카 & 유럽)
      head: [],
      armor: [],
      weapon: [],
      ring: [],
      amulet: [],
      hole: [
        12,24,
        100,113,114,115,133,134,135,
        100,113,114,115,133,134,135
      ],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    // 인도양(아시아 -> 아프리카 & 중동)
  ],
  job: [
    {// 군주
      head: [1,4,6],
      armor: [6,8,10],
      weapon: [1,5,8],
      ring: [0],
      amulet: [0],
      hole: [],
      upgrade: [],
      material: [],
      etc:[0],
      money:500,
    },
    {// 마법사
      head: [0,2],
      armor: [3,6],
      weapon: [8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:100,
    },
    {// 기사
      head: [6,7],
      armor: [8,10,11],
      weapon: [1,2,4,8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[0],
      money:100,
    },
    {// 무사
      head: [1,4],
      armor: [5,6,9],
      weapon: [1,2,8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[3,4],
      money:0,
    },
    {// 학자
      head: [0,2],
      armor: [1],
      weapon: [0,9],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:100,
    },
    {// 닌자
      head: [0],
      armor: [2,4],
      weapon: [0,1,7],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    {// 도술사
      head: [0,5],
      armor: [1,2],
      weapon: [3,7,9],
      ring: [],
      amulet: [0],
      hole: [],
      upgrade: [],
      material: [],
      etc:[21],
      money:0,
    },
    {// 무희
      head: [0],
      armor: [0,1,2],
      weapon: [0,7,9],
      ring: [0],
      amulet: [0],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:300,
    },
    {// 도적
      head: [1,2],
      armor: [1,2,4],
      weapon: [0,3,5,6],
      ring: [0],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[24],
      money:0,
    },
    {// 궁수
      head: [1],
      armor: [2,4,5],
      weapon: [0,6],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:100,
    },
    {// 야만인
      head: [3,5],
      armor: [7,8],
      weapon: [2,3,5,8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[3,4],
      money:0,
    },
    {// 상인
      head: [2],
      armor: [3,7],
      weapon: [3,7,8],
      ring: [0],
      amulet: [0],
      hole: [],
      upgrade: [],
      material: [],
      etc:[0,1],
      money:1000,
    },
    {// 한량
      head: [],
      armor: [0,4],
      weapon: [5,7,9],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:0,
    },
    {// 장군
      head: [3,4],
      armor: [6,10],
      weapon: [1,2,8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[0],
      money:100,
    },
    {// 농부
      head: [2,3],
      armor: [1,3,5],
      weapon: [3,4,5,9],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:200,
    },
    {// 의술사
      head: [0],
      armor: [1,3],
      weapon: [0,9],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:100,
    },
    {// 기술자
      head: [3,6],
      armor: [5,7],
      weapon: [3,5,8],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[22],
      money:100,
    },
    {// 어부
      head: [2,3],
      armor: [1,3,5],
      weapon: [3,4,5,9],
      ring: [],
      amulet: [],
      hole: [],
      upgrade: [],
      material: [],
      etc:[],
      money:200,
    },
  ],
  shop: [

  ],
  dungeon: [
    {

    },
  ],
  hero: [

  ],
}