//직업스킬
export const job = [
  {idx:0,
    na:{
      ko:'군주',
      en:'Lords',
      jp:'君主',
    },
    txt:{
      ko:'이 직업은 리더쉽을 바탕으로 부대를 통솔 할 수 있습니다.',
      en:'This profession allows you to command troops based on leadership.',
      jp:'この職業は、リーダーシップをもとに部隊を統率することができます。',
    },
    skill:{//단검,검,양손검,둔기,창,도끼,활,타격,방패,
      type:'random',
      initialCounts:3,
      basic:[24,25,26,27,28,29],
      lv0:[], //45%
      lv1:[15,20,22], //40%
      lv2:[24,25,26,27,28,29], //15%
      lv3:[9,10], //15%
      maxLv:[0,1,2,9,10,15,20,22],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-1', '1-0-0-4', '1-0-0-6',
        '2-0-0-6', '2-0-0-8', '2-0-0-10',
        '3-0-1', '3-0-5', '3-0-8',
        '4-0-0',
        '5-0-0',
      ],
      hole:[],
    }},
  {idx:1,
    na:{
      ko:'마법사',
      en:'Wizards',
      jp:'ウィザード',
    },
    txt:{
      ko:'이 직업은 자연계 술법에 능통하고 최대 2개의 속성을 연마할 수 있습니다.',
      en:'This class is proficient in natural arts and can hone up to two attributes.',
      jp:'この職業は自然界術法に精通しており、最大2つの属性を磨くことができます。',
    },
    skill:{//단검,검,한손둔기,보조,
      type:'choose', //물, 불, 바람, 땅
      initialCounts:2,
      basic:[5,6,7,8],
      lv0:[],
      lv1:[15,24,25,27],
      lv2:[],
      lv3:[11,12,13,14],
      maxLv:[0,1,2,11,12,13,14,15],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0', '1-0-0-2',
        '2-0-0-3', '2-0-0-6',
        '3-0-8', 
      ],
      hole:[],
    }},
  {idx:2,
    na:{
      ko:'기사',
      en:'Knight',
      jp:'騎士',
    },
    txt:{
      ko:'이 직업은 무거운 장비까지 착용이 가능하여 방어력이 뛰어나고 대부분의 공격을 무효화 시킵니다.',
      en:'This class can wear up to heavy equipment, giving it great defense and negating most attacks.',
      jp:'この職業は重い装備まで着用でき、防御力に優れ、ほとんどの攻撃を無効化します。',
    },
    skill:{//검,양손검,둔기,창,도끼,방패,
      type:'choose', //방어스킬, 공격스킬
      initialCounts:2,
      basic:[24,25,26,27,28],
      lv0:[],
      lv1:[],
      lv2:[24,25,26,27,28],
      lv3:[14],
      maxLv:[0,1,2,14],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-6', '1-0-0-7',
        '2-0-0-8', '2-0-0-10', '2-0-0-11',
        '3-0-1', '3-0-2', '3-0-4', '3-0-8',
      ],
      hole:[],
    }},
  {idx:3,
    na:{
      ko:'무사',
      en:'Warrior',
      jp:'武士',
    },
    txt:{
      ko:'이 직업은 다양한 무기에 통달하여 특히 일대일 전투에서 진가가 들어납니다.',
      en:'This class is particularly effective in one-on-one combat due to its mastery of a variety of weapons.',
      jp:'このクラスは様々な武器に精通しており、特に1対1の戦闘で威力を発揮します。',
    },
    skill:{//단검,검,양손검,한손둔기,창,
      type:'random',
      initialCounts:1,
      basic:[24,25,27],
      lv0:[],
      lv1:[],
      lv2:[17,24,25,27],
      lv3:[12],
      maxLv:[0,1,2,12,17],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-1', '1-0-0-4',
        '2-0-0-5', '2-0-0-6', '2-0-0-9',
        '3-0-1', '3-0-2', '3-0-8',
      ],
      hole:[],
    }},
  {idx:4,
    na:{
      ko:'학자',
      en:'Scholar',
      jp:'学者',
    },
    txt:{
      ko:'이 직업은 많은 지식을 연구하고 발전시킨 직업으로 전투에 약합니다.',
      en:'This is a class that has studied and developed a lot of knowledge and is weak in combat.',
      jp:'この職業は多くの知識を研究・発展させた職業で、戦闘に弱いです。',
    },
    skill:{//단검,검,타격,방패,보조,
      type:'choose',//전투스킬, 직업스킬
      initialCounts:1,
      basic:[],
      lv0:[],
      lv1:[24,25,27,28],
      lv2:[15,20,22],
      lv3:[],
      maxLv:[0,1,2,15,20,22],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0','1-0-0-2',
        '2-0-0-1',
        '3-0-0', '3-0-9',
      ],
      hole:[],
    }},
  {idx:5,
    na:{
      ko:'닌자',
      en:'Ninja',
      jp:'忍者',
    },
    txt:{
      ko:'이 직업은 마음의 수양을 통해 정신의 한계를 극복한 직업으로 암기에 능통합니다.',
      en:'This is a profession that has overcome the limitations of the mind through the discipline of the heart and is adept at memorization.',
      jp:'この職業は、心の修養によって精神の限界を克服した職業で、暗記に長けています。',
    },
    skill:{//단검,검,한손둔기,한손도끼,타격,
      type:'random',
      initialCounts:1,
      basic:[10,24,25,26,27],
      lv0:[],
      lv1:[],
      lv2:[24,25,26,27],
      lv3:[10],
      maxLv:[0,1,2,10],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0',
        '2-0-0-2', '2-0-0-4',
        '3-0-0', '3-0-1', '3-0-7',//쌍수
      ],
      hole:[4],
    }},
  {idx:6,
    na:{
      ko:'도술사',
      en:'Shaman',
      jp:'占い師',
    },
    txt:{
      ko:'이 직업은 선 또는 악을 연구하는 직업으로 상당히 강력합니다.',
      en:'This class is quite powerful as a study of good or evil.',
      jp:'この職業は善悪を研究する職業で、かなり強力です。',
    },
    skill:{//한손둔기,타격,보조,
      type:'choose',//빛, 어둠
      initialCounts:1,
      basic:[3,4],
      lv0:[],
      lv1:[27],
      lv2:[20],
      lv3:[9,10],
      maxLv:[0,1,2,9,10,20],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0', '1-0-0-5',
        '2-0-0-1', '2-0-0-2',
        '3-0-3', '3-0-7', '3-0-9',
        '5-0-0',
      ],
      hole:[],
    }},
  {idx:7,
    na:{
      ko:'무희',
      en:'Dancer',
      jp:'踊り子',
    },
    txt:{
      ko:'이 직업은 정신술법에 특화된 직업으로 남성에게 특히 강합니다.',
      en:'This class specializes in mentalism and is particularly strong for men.',
      jp:'この職業は精神術法に特化した職業で、男性に特に強いです。',
    },
    skill:{//단검,검,활,타격,보조,
      type:'random',
      initialCounts:1,
      basic:[24,25,27,29],
      lv0:[],
      lv1:[24,25,27,29],
      lv2:[15,22,23],
      lv3:[],
      maxLv:[0,1,2,15,22,23],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0',
        '2-0-0-0', '2-0-0-1', '2-0-0-2',
        '3-0-0', '3-0-7', '3-0-9',
        '4-0-0',
        '5-0-0',
      ],
      hole:[],
    }},
  {idx:8,
    na:{
      ko:'도적',
      en:'Rogue',
      jp:'盗賊',
    },
    txt:{
      ko:'이 직업은 빠른 속도를 기반으로 적을 농락합니다.',
      en:'This class relies on speed to outmaneuver enemies.',
      jp:'このクラスはスピードで敵を翻弄する。',
    },
    skill:{//단검,검,한손둔기,활,타격,
      type:'choose',//활, 단검
      initialCounts:1,
      basic:[24,25,27,29],
      lv0:[],
      lv1:[],
      lv2:[15,22,24,25,27,29],
      lv3:[],
      maxLv:[0,1,2,15,22],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-1', '1-0-0-2',
        '2-0-0-1', '2-0-0-2', '2-0-0-4',
        '3-0-0', '3-0-3', '3-0-5', '3-0-6',//쌍수
        '4-0-0',
      ],
      hole:[],
    }},
  {idx:9,
    na:{
      ko:'궁수',
      en:'Archer',
      jp:'射手',
    },
    txt:{
      ko:'이 직업은 원거리에서 광 범위한 영역에 공격이 가능한 직업입니다.',
      en:'This is a class that can attack a large area from a distance.',
      jp:'この職業は遠距離から広範囲のエリアに攻撃が可能な職業です。',
    },
    skill:{//단검,검,활,타격,방패,
      type:'random',
      initialCounts:1,
      basic:[24,25,28,29],
      lv0:[],
      lv1:[],
      lv2:[24,25,28,29],
      lv3:[],
      maxLv:[0,1,2],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-1',
        '2-0-0-2', '2-0-0-4', '2-0-0-5',
        '3-0-0', '3-0-6',//쌍수
      ],
      hole:[],
    }},
  {idx:10,
    na:{
      ko:'야만용사',
      en:'Barbarian',
      jp:'野蛮人',
    },
    txt:{
      ko:'이 직업은 자연을 통해 강화시킨 신체능력으로 전쟁에서 중요한 역할을 합니다.',
      en:'This class plays an important role in warfare with physical abilities enhanced by nature.',
      jp:'この職業は自然を通じて強化した身体能力で戦争で重要な役割を果たします。',
    },
    skill:{//단검,검,양손검,둔기,창,도끼,활,타격,방패,
      type:'choose',//도끼, 창, 양손검
      initialCounts:1,
      basic:[24,25,26,27,28,29],
      lv0:[],
      lv1:[],
      lv2:[24,25,26,27,28,29],
      lv3:[],
      maxLv:[0,1,2],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-3', '1-0-0-5',
        '2-0-0-7', '2-0-0-8',
        '3-0-2', '3-0-3', '3-0-5', '3-0-8',
      ],
      hole:[],
    }},
  {idx:11,
    na:{
      ko:'상인',
      en:'Merchant',
      jp:'商人',
    },
    txt:{
      ko:'이 직업은 숫자에 능한 직업으로 돈 버는 능력이 탁월합니다.',
      en:'This is a job where you\'re good with numbers, and you\'re good at making money.',
      jp:'この職業は数字に強い職業で、お金を稼ぐ能力に優れています。',
    },
    skill:{//단검,검,양손검,둔기,도끼,활,타격,방패,
      type:'random',
      initialCounts:3,
      basic:[],
      lv0:[],
      lv1:[24,25,26,27,28,29],
      lv2:[15,17],
      lv3:[],
      maxLv:[0,1,2,15,17],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-2',
        '2-0-0-3', '2-0-0-7',
        '3-0-3', '3-0-7', '3-0-8',
        '4-0-0',
        '5-0-0',
      ],
      hole:[],
    }},
  {idx:12,
    na:{
      ko:'한량',
      en:'Scammers',
      jp:'詐欺師',
    },
    txt:{
      ko:'이 직업은 하루 종일 놀고 먹는 직업이며 대체로 행운이 따릅니다.',
      en:'This job is day job to play and eat, and generally good luck.',
      jp:'この仕事は一日中遊んだり食べたりする仕事で、一般的に運がつきものです。',
    },
    skill:{//단검,둔기,창,도끼,타격,
      type:'random',
      initialCounts:2,
      basic:[13,24,26,27],
      lv0:[],
      lv1:[24,26,27],
      lv2:[15,21],
      lv3:[13],
      maxLv:[0,1,2,13,15,21],
    },
    drop:{
      gold:100,
      equip:[
        '2-0-0-0', '2-0-0-4', 
        '3-0-5', '3-0-7', '3-0-9'//쌍수
      ],
      hole:[],
    }},
  {idx:13,
    na:{
      ko:'장군',
      en:'General',
      jp:'将軍',
    },
    txt:{
      ko:'이 직업은 전쟁의 승패를 좌지우지 하는 전쟁에 특화된 직업입니다.',
      en:'This class specializes in warfare, which can mean the difference between winning and losing a war.',
      jp:'この職業は戦争の勝敗を左右する戦争に特化した職業です。',
    },
    skill:{//단검,검,양손검,둔기,창,도끼,활,타격,방패,
      type:'random',
      initialCounts:3,
      basic:[24,25,26,27,28,29],
      lv0:[],
      lv1:[],
      lv2:[22,24,25,26,27,28,29],
      lv3:[11],
      maxLv:[0,1,2,11,22],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-3', '1-0-0-4',
        '2-0-0-6', '2-0-0-10',
        '3-0-1', '3-0-2', '3-0-8',
      ],
      hole:[],
    }},
  {idx:14,
    na:{
      ko:'농부',
      en:'Farmer',
      jp:'農家',
    },
    txt:{
      ko:'이 직업은 일반적인 직업으로 체력이 좋습니다.',
      en:'This is a common job and requires good stamina.',
      jp:'この職業は一般的な職業で体力があります。',
    },
    skill:{//단검,검,둔기,창,도끼,타격,
      type:'random',
      initialCounts:2,
      basic:[],
      lv0:[],
      lv1:[24,25,26,27],
      lv2:[17,19],
      lv3:[],
      maxLv:[0,1,2,17,19],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-2', '1-0-0-3',
        '2-0-0-1', '2-0-0-3', '2-0-0-5',
        '3-0-3', '3-0-4', '3-0-5', '3-0-9',
      ],
      hole:[],
    }},
  {idx:15,
    na:{
      ko:'의술사',
      en:'Physician',
      jp:'医術師',
    },
    txt:{
      ko:'이 직업은 회복에 특화된 직업으로 전투시 보조를 담당합니다.',
      en:'This class specializes in healing and aids in combat.',
      jp:'この職業は回復に特化した職業で、戦闘時の補助を担当する。',
    },
    skill:{//단검,검,둔기,도끼,보조,
      type:'random',
      initialCounts:2,
      basic:[],
      lv0:[],
      lv1:[24,25,26,27],
      lv2:[15,22],
      lv3:[],
      maxLv:[0,1,2,15,22],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-0',
        '2-0-0-1', '2-0-0-3',
        '3-0-0', '3-0-9',
      ],
      hole:[],
    }},
  {idx:16,
    na:{
      ko:'기술자',
      en:'Technician',
      jp:'技術者',
    },
    txt:{
      ko:'이 직업은 도구 및 장비에 대한 높은 지식을 바탕으로 생산적인 역할을 담당합니다.',
      en:'This job is a productive role with a high knowledge of tools and equipment.',
      jp:'この職業は、工具や設備に関する高い知識をもとに生産的な役割を担います。',
    },
    skill:{//단검,둔기,도끼,타격,방패,보조,
      type:'random',
      initialCounts:2,
      basic:[],
      lv0:[],
      lv1:[24,26,27,28],
      lv2:[16,17,18,20,21,23],
      lv3:[],
      maxLv:[0,1,2,16,17,18,20,21,23],
    },
    drop:{
      gold:100,
      equip:[
        '1-0-0-3', '1-0-0-6',
        '2-0-0-5', '2-0-0-7',
        '3-0-3', '3-0-5', '3-0-8',
      ],
      hole:[],
    }},
]

// * 0군주 - 빛의정령, 어둠의정령
// * 1마법사 - (불의정령, 물의정령, 바람의정령, 땅의정령 중 3가지 종류만 제공) 택1,
// * 2기사 -
// * 3무사 -
// * 4학자 -
// * 5닌자 - 어둠의정령
// * 6도인 - (빛의정령, 어둠의정령) 택1
// * 7무희 - 빛의정령
// * 8도적 -
// * 9궁수 -
// * 10야만용사 -
// * 11상인 -
// * 12한량 -
// * 13장군 -
// * 14농부 -
// * 15의술사 -
// * 16기술자 -