export const save = {
    "info":{
      id:'OngbakKai',
      lv:34,
      diamond:28200,
      money:352000
    },
    "ch":[
      {"idx":0,"stateType":0,"element":[11],"stateLuk":146,"lv":15,"exp":10,"hasExp":50000,"actionPoint":20,"sk":[{"idx":1,"lv":2,"exp":40},{"idx":2,"lv":3,"exp":90},{"idx":3,"lv":1,"exp":0},{"idx":13,"lv":1,"exp":0}],"items":[
        {"idx":5,"slot":0,"hole":[4,0,12,23],"lv":1,"upgrade":1},
        {},
        {"idx":11,"slot":3,"hole":[],"lv":1,"upgrade":2},
        {},
        {"idx":2,"slot":2,"hole":[0,0,0],"lv":1,"upgrade":1},
        {},
        {},
        {},
      ]},
      {"idx":1,"stateType":0,"element":[8],"stateLuk":20,"lv":10,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1},{"idx":2,"lv":1},{"idx":8,"lv":1}],"items":[
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},]},
      {"idx":4,"stateType":0,"element":[10],"stateLuk":95,"lv":50,"exp":0,"hasExp":9000,"actionPoint":20,"sk":[{"idx":1,"lv":1},{"idx":2,"lv":1},{"idx":9,"lv":1}],"items":[
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},]},
      {"idx":7,"stateType":0,"element":[6],"stateLuk":35,"lv":50,"exp":10,"hasExp":5000,"actionPoint":20,"sk":[{"idx":1,"lv":3,"exp":90},{"idx":2,"lv":5,"exp":70},{"idx":3,"lv":30,"exp":0},{"idx":4,"lv":30,"exp":0}],"items":[
        {"idx":5,"slot":0,"hole":[4,0,12,23],"lv":1,"upgrade":1},
        {},
        {"idx":3,"slot":3,"hole":[],"lv":1,"upgrade":2},
        {},
        {},
        {"idx":2,"slot":2,"hole":[0,0,0],"lv":1,"upgrade":1},
        {},
        {},
      ]},
      // {"idx":4,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":5,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":6,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":7,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":8,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":9,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":10,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":11,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":12,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":13,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":14,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":15,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":16,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":17,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},
      //   {},]},
      // {"idx":18,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[]},
      // {"idx":19,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[]},
      // {"idx":20,"stateType":0,"lv":50,"exp":0,"hasExp":1000,"actionPoint":20,"sk":[{"idx":1,"lv":1}],"items":[]},
    ],
    "items":{
      "equip":[
        {"idx":10,"slot":0,"hole":[],"lv":1,"upgrade":1},
        {"idx":11,"slot":0,"hole":[],"lv":1,"upgrade":1},
        {"idx":12,"slot":0,"hole":[],"lv":1,"upgrade":1},
        {"idx":5,"slot":0,"hole":[],"lv":1,"upgrade":1},
        {"idx":3,"slot":3,"hole":[],"lv":1,"upgrade":2},
        {"idx":1,"slot":1,"hole":[1],"lv":1,"upgrade":0}
      ],
      "hole":[
        {"idx":1},
        {"idx":3},
        {"idx":10},
        {"idx":20},
        {"idx":22},
        {"idx":23},
      ],
      "upgrade":[
        {"idx":1},
        {"idx":4},
        {"idx":2},
        {"idx":1},
        {"idx":4},
      ],
      "material":[
      ],
      "etc":[
        {"idx":3},
        {"idx":3},
        {"idx":4},
        {"idx":5},
        {"idx":6},
        {"idx":7},
        {"idx":0},
        {"idx":1},
        {"idx":21},
        {"idx":10},
        {"idx":2},
        {"idx":20},
        {"idx":1},
        {"idx":21},
        {"idx":10},
        {"idx":2},
        {"idx":10},
        {"idx":2},
        {"idx":20},
        {"idx":1},
        {"idx":21},
        {"idx":10},
        {"idx":2},
      ]
    },
    "lineup":{
      "select":0,
      "save_slot":[
        {"no":1, "entry":["","",0,"","","",1,"",2,"",3,"","","","","","","","","","","","","",""], "num":4},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
        {"no":0, "entry":["","","","","","","","","","","","","","","","","","","","","","","","",""], "num":0},
      ]
    }
  }